<a href="https://colab.research.google.com/github/JasonKeha/Structured_Query_Language-SQL-/blob/main/SQL_Summer_Olympic_Medals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **SQL Summer Olympic Medals**

*Original dataset:* (https://www.kaggle.com/datasets/ramontanoeiro/summer-olympic-medals-1986-2020)

### Importing the necessary libraries to work SQL queries using python

In [ ]:
import sqlite3 as sql
import pandas as pd
import csv

### Connecting to our database

In [ ]:
pip install opendatasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from opendatasets) (8.1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from opendatasets) (4.65.0)
Requirement already satisfied: kaggle in /usr/local/lib/python3.9/dist-packages (from opendatasets) (1.5.13)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.26.14)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.25.1)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (8.0.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from kaggle->opendatasets) (2022.12.7)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.9/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests->kaggle->opendatasets) (4.0.0)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [ ]:
import opendatasets as od

API Details

Username : itsjasonk

Key : 0fdaa64cb05419c3c1403b05d9aec00d

In [ ]:
od.download('https://www.kaggle.com/datasets/ramontanoeiro/summer-olympic-medals-1986-2020')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: itsjasonk
Your Kaggle Key: ··········
Downloading summer-olympic-medals-1986-2020.zip to ./summer-olympic-medals-1986-2020

100%|██████████| 9.57k/9.57k [00:00<00:00, 6.34MB/s]

### Getting the data to format the dataset to work with it in SQL

In [ ]:
df = pd.read_csv('/content/summer-olympic-medals-1986-2020/Summer_olympic_Medals.csv')
df

,Year,Host_country,Host_city,Country_Name,Country_Code,Gold,Silver,Bronze
0,1896,Greece,Athens,Great Britain,GBR,2,3,2
1,1896,Greece,Athens,Hungary,HUN,2,1,3
2,1896,Greece,Athens,France,FRA,5,4,2
3,1896,Greece,Athens,United States,USA,11,7,2
4,1896,Greece,Athens,Germany,GER,6,5,2
...,...,...,...,...,...,...,...,...
1339,2020,Japan,Tokyo,Fiji,FIJ,1,0,1
1340,2020,Japan,Tokyo,Estonia,EST,1,0,1
1341,2020,Japan,Tokyo,Latvia,LAT,1,0,1
1342,2020,Japan,Tokyo,Bermuda,BER,1,0,0
1343,2020,Japan,Tokyo,Thailand,THA,1,0,1

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

### Defining our SQL connection

In [ ]:
conn = sql.connect('olympic_medals.db')

In [ ]:
c = conn.cursor()

In [ ]:
c.execute('''CREATE TABLE olympic_medals
             (Year INTEGER, Host_country TEXT, Host_city TEXT, Country_Name TEXT,
             Country_Code TEXT, Gold INTEGER, Silver INTEGER, Bronze INTEGER)''')

In [ ]:
with open('/content/summer-olympic-medals-1986-2020/Summer_olympic_Medals.csv', 'r') as f:
    next(f) # skip the header row
    csv_reader = csv.reader(f)
    for row in csv_reader:
        c.execute('INSERT INTO olympic_medals VALUES (?, ?, ?, ?, ?, ?, ?, ?)', row)
conn.commit()

### Checking our SQL dataset

In [ ]:
query_check = '''
SELECT * FROM olympic_medals
'''
pd.read_sql_query(query_check, conn)
# Everything seems okay

,Year,Host_country,Host_city,Country_Name,Country_Code,Gold,Silver,Bronze
0,1896,Greece,Athens,Great Britain,GBR,2,3,2
1,1896,Greece,Athens,Hungary,HUN,2,1,3
2,1896,Greece,Athens,France,FRA,5,4,2
3,1896,Greece,Athens,United States,USA,11,7,2
4,1896,Greece,Athens,Germany,GER,6,5,2
5,1896,Greece,Athens,Austria,AUT,2,1,2
6,1896,Greece,Athens,Mixed team,ZZX,1,0,1
7,1896,Greece,Athens,Greece,GRE,10,18,19
8,1896,Greece,Athens,Switzerland,SUI,1,2,0
9,1896,Greece,Athens,Australia,AUS,2,0,0
10,1896,Greece,Athens,Denmark,DEN,1,2,3
11,1900,France,Paris,Italy,ITA,3,2,0
12,1900,France,Paris,Germany,GER,4,3,2
13,1900,France,Paris,Australia,AUS,2,0,3
14,1900,France,Paris,Hungary,HUN,1,2,2
15,1900,France,Paris,Denmark,DEN,1,3,2
16,1900,France,Paris,France,FRA,27,38,37
17,1900,France,Paris,Switzerland,SUI,6,2,1
18,1900,France,Paris,United States,USA,19,14,15
19,1900,France,Paris,Mixed team,ZZX,8,5,6
20,1900,France,Paris,Great Britain,GBR,15,8,9
21,1900,France,Paris,Cuba,CUB,1,1,0
22,1900,France,Paris,India,IND,0,2,0
23,1900,France,Paris,Netherlands,NED,0,2,3
24,1900,France,Paris,Bohemia,BOH,0,1,1
25,1900,France,Paris,Belgium,BEL,6,7,4
26,1900,France,Paris,Sweden,SWE,0,0,1
27,1900,France,Paris,Spain,ESP,1,0,0
28,1900,France,Paris,Canada,CAN,1,0,1
29,1900,France,Paris,Luxembourg,LUX,1,0,0
30,1900,France,Paris,Norway,NOR,0,2,3
31,1900,France,Paris,Austria,AUT,0,3,3
32,1904,United States,St. Louis,Cuba,CUB,3,0,0
33,1904,United States,St. Louis,Hungary,HUN,2,1,1
34,1904,United States,St. Louis,Mixed team,ZZX,2,1,1
35,1904,United States,St. Louis,United States,USA,76,78,77
36,1904,United States,St. Louis,Germany,GER,4,5,6
37,1904,United States,St. Louis,Canada,CAN,4,1,1
38,1904,United States,St. Louis,Greece,GRE,1,0,1
39,1904,United States,St. Louis,Australia,AUS,0,3,1
40,1904,United States,St. Louis,France,FRA,0,1,0
41,1904,United States,St. Louis,Switzerland,SUI,1,0,2
42,1904,United States,St. Louis,Norway,NOR,2,0,0
43,1904,United States,St. Louis,Austria,AUT,1,1,1
44,1904,United States,St. Louis,Great Britain,GBR,1,1,0
45,1908,Great Britain,London,Canada,CAN,3,3,10
46,1908,Great Britain,London,Hungary,HUN,3,4,2
47,1908,Great Britain,London,Italy,ITA,2,2,0
48,1908,Great Britain,London,Norway,NOR,2,3,3
49,1908,Great Britain,London,Germany,GER,3,5,5
50,1908,Great Britain,London,United States,USA,23,12,12
51,1908,Great Britain,London,Great Britain,GBR,56,51,39
52,1908,Great Britain,London,France,FRA,5,5,9
53,1908,Great Britain,London,Sweden,SWE,8,6,11
54,1908,Great Britain,London,Denmark,DEN,0,2,3
55,1908,Great Britain,London,Greece,GRE,0,3,1
56,1908,Great Britain,London,Bohemia,BOH,0,0,2
57,1908,Great Britain,London,Austria,AUT,0,0,1
58,1908,Great Britain,London,Netherlands,NED,0,0,2
59,1908,Great Britain,London,Australasia,ANZ,1,2,2
60,1908,Great Britain,London,Belgium,BEL,1,5,2
61,1908,Great Britain,London,Russian Empire,RU1,1,2,0
62,1908,Great Britain,London,South Africa,RSA,1,1,0
63,1908,Great Britain,London,Finland,FIN,1,1,3
64,1912,Sweden,Stockholm,Germany,GER,6,13,7
65,1912,Sweden,Stockholm,Italy,ITA,5,1,2
66,1912,Sweden,Stockholm,Norway,NOR,4,1,5
67,1912,Sweden,Stockholm,South Africa,RSA,4,2,0
68,1912,Sweden,Stockholm,Sweden,SWE,24,24,17
69,1912,Sweden,Stockholm,United States,USA,26,19,19
70,1912,Sweden,Stockholm,France,FRA,7,5,3
71,1912,Sweden,Stockholm,Finland,FIN,9,8,9
72,1912,Sweden,Stockholm,Canada,CAN,3,2,3
73,1912,Sweden,Stockholm,Russian Empire,RU1,0,2,3
74,1912,Sweden,Stockholm,Switzerland,SUI,1,0,0
75,1912,Sweden,Stockholm,Netherlands,NED,0,0,3
76,1912,Sweden,Stockholm,Austria,AUT,0,2,2
77,1912,Sweden,Stockholm,Greece,GRE,1,0,1
78,1912,Sweden,Stockholm,Australasia,ANZ,2,2,3
79,1912,Sweden,Stockholm,Hungary,HUN,3,2,3
80,1912,Sweden,Stockholm,Denmark,DEN,1,6,5
81,1912,Sweden,Stockholm,Belgium,BEL,2,1,3
82,1912,Sweden,Stockholm,Great Britain,GBR,10,15,16
83,1920,Belgium,Antwerp,Switzerland,SUI,2,2,7
84,1920,Belgium,Antwerp,Brazil,BRA,1,1,1
85,1920,Belgium,Antwerp,Australia,AUS,0,2,1
86,1920,Belgium,Antwerp,Denmark,DEN,3,9,1
87,1920,Belgium,Antwerp,South Africa,RSA,3,4,3
88,1920,Belgium,Antwerp,Canada,CAN,3,3,3
89,1920,Belgium,Antwerp,Luxembourg,LUX,0,1,0
90,1920,Belgium,Antwerp,Czechoslovakia,TCH,0,0,2
91,1920,Belgium,Antwerp,New Zealand,NZL,0,0,1
92,1920,Belgium,Antwerp,Japan,JPN,0,2,0
93,1920,Belgium,Antwerp,Spain,ESP,0,2,0
94,1920,Belgium,Antwerp,Greece,GRE,0,1,0
95,1920,Belgium,Antwerp,Netherlands,NED,4,2,5
96,1920,Belgium,Antwerp,Belgium,BEL,16,12,14
97,1920,Belgium,Antwerp,Finland,FIN,15,10,9
98,1920,Belgium,Antwerp,Sweden,SWE,19,20,25
99,1920,Belgium,Antwerp,Estonia,EST,1,2,0
100,1920,Belgium,Antwerp,United States,USA,41,27,27
101,1920,Belgium,Antwerp,France,FRA,9,19,13
102,1920,Belgium,Antwerp,Italy,ITA,13,5,5
103,1920,Belgium,Antwerp,Norway,NOR,13,9,9
104,1920,Belgium,Antwerp,Great Britain,GBR,14,16,13
105,1924,France,Paris,Norway,NOR,5,2,3
106,1924,France,Paris,Sweden,SWE,4,13,12
107,1924,France,Paris,Denmark,DEN,2,5,2
108,1924,France,Paris,Netherlands,NED,4,1,5
109,1924,France,Paris,Belgium,BEL,3,7,3
110,1924,France,Paris,Australia,AUS,3,1,2
111,1924,France,Paris,Switzerland,SUI,7,8,10
112,1924,France,Paris,France,FRA,13,15,10
113,1924,France,Paris,Finland,FIN,14,13,10
114,1924,France,Paris,United States,USA,45,27,27
115,1924,France,Paris,Italy,ITA,8,3,5
116,1924,France,Paris,Great Britain,GBR,9,13,12
117,1924,France,Paris,Haiti,HAI,0,0,1
118,1924,France,Paris,Hungary,HUN,2,3,4
119,1924,France,Paris,Romania,ROU,0,0,1
120,1924,France,Paris,Poland,POL,0,1,1
121,1924,France,Paris,Canada,CAN,0,3,1
122,1924,France,Paris,Japan,JPN,0,0,1
123,1924,France,Paris,New Zealand,NZL,0,0,1
124,1924,France,Paris,Portugal,POR,0,0,1
125,1924,France,Paris,Austria,AUT,0,3,1
126,1924,France,Paris,Argentina,ARG,1,3,2
127,1924,France,Paris,Czechoslovakia,TCH,1,4,5
128,1924,France,Paris,Yugoslavia,YUG,2,0,0
129,1924,France,Paris,Uruguay,URU,1,0,0
130,1924,France,Paris,South Africa,RSA,1,1,1
131,1924,France,Paris,Estonia,EST,1,1,4
132,1928,Netherlands,Amsterdam,Great Britain,GBR,3,10,7
133,1928,Netherlands,Amsterdam,Canada,CAN,4,4,7
134,1928,Netherlands,Amsterdam,Hungary,HUN,4,5,0
135,1928,Netherlands,Amsterdam,Czechoslovakia,TCH,2,5,2
136,1928,Netherlands,Amsterdam,Japan,JPN,2,2,1
137,1928,Netherlands,Amsterdam,Argentina,ARG,3,3,1
138,1928,Netherlands,Amsterdam,Denmark,DEN,3,1,2
139,1928,Netherlands,Amsterdam,Netherlands,NED,6,9,4
140,1928,Netherlands,Amsterdam,Germany,GER,10,7,14
141,1928,Netherlands,Amsterdam,Finland,FIN,8,8,9
142,1928,Netherlands,Amsterdam,South Africa,RSA,1,0,2
143,1928,Netherlands,Amsterdam,United States,USA,22,18,16
144,1928,Netherlands,Amsterdam,Switzerland,SUI,7,4,4
145,1928,Netherlands,Amsterdam,France,FRA,6,10,5
146,1928,Netherlands,Amsterdam,Sweden,SWE,7,6,12
147,1928,Netherlands,Amsterdam,Italy,ITA,7,5,7
148,1928,Netherlands,Amsterdam,Estonia,EST,2,1,2
149,1928,Netherlands,Amsterdam,Uruguay,URU,1,0,0
150,1928,Netherlands,Amsterdam,Belgium,BEL,0,1,2
151,1928,Netherlands,Amsterdam,New Zealand,NZL,1,0,0
152,1928,Netherlands,Amsterdam,Spain,ESP,1,0,0
153,1928,Netherlands,Amsterdam,Philippines,PHI,0,0,1
154,1928,Netherlands,Amsterdam,Portugal,POR,0,0,1
155,1928,Netherlands,Amsterdam,Chile,CHI,0,1,0
156,1928,Netherlands,Amsterdam,Haiti,HAI,0,1,0
157,1928,Netherlands,Amsterdam,Australia,AUS,1,2,1
158,1928,Netherlands,Amsterdam,Norway,NOR,1,2,1
159,1928,Netherlands,Amsterdam,Egypt,EGY,2,1,1
160,1928,Netherlands,Amsterdam,Austria,AUT,2,0,1
161,1928,Netherlands,Amsterdam,India,IND,1,0,0
162,1928,Netherlands,Amsterdam,Ireland,IRL,1,0,0
163,1928,Netherlands,Amsterdam,Poland,POL,1,1,3
164,1928,Netherlands,Amsterdam,Yugoslavia,YUG,1,1,3
165,1932,United States,Los Angeles,Argentina,ARG,3,1,0
166,1932,United States,Los Angeles,Australia,AUS,3,1,1
167,1932,United States,Los Angeles,Germany,GER,3,12,5
168,1932,United States,Los Angeles,Poland,POL,2,1,4
169,1932,United States,Los Angeles,Netherlands,NED,2,5,0
170,1932,United States,Los Angeles,Canada,CAN,2,5,8
171,1932,United States,Los Angeles,Great Britain,GBR,4,7,5
172,1932,United States,Los Angeles,Sweden,SWE,9,5,9
173,1932,United States,Los Angeles,France,FRA,10,5,4
174,1932,United States,Los Angeles,Italy,ITA,12,12,12
175,1932,United States,Los Angeles,Finland,FIN,5,8,12
176,1932,United States,Los Angeles,Hungary,HUN,6,4,5
177,1932,United States,Los Angeles,Japan,JPN,7,7,4
178,1932,United States,Los Angeles,South Africa,RSA,2,0,3
179,1932,United States,Los Angeles,Philippines,PHI,0,0,3
180,1932,United States,Los Angeles,Switzerland,SUI,0,1,0
181,1932,United States,Los Angeles,New Zealand,NZL,0,1,0
182,1932,United States,Los Angeles,United States,USA,41,32,30
183,1932,United States,Los Angeles,Uruguay,URU,0,0,1
184,1932,United States,Los Angeles,Spain,ESP,0,0,1
185,1932,United States,Los Angeles,Latvia,LAT,0,1,0
186,1932,United States,Los Angeles,Austria,AUT,1,1,3
187,1932,United States,Los Angeles,Czechoslovakia,TCH,1,2,1
188,1932,United States,Los Angeles,Ireland,IRL,2,0,0
189,1932,United States,Los Angeles,Mexico,MEX,0,2,0
190,1932,United States,Los Angeles,Denmark,DEN,0,3,3
191,1932,United States,Los Angeles,India,IND,1,0,0
192,1936,Germany,Berlin,Great Britain,GBR,4,7,3
193,1936,Germany,Berlin,Austria,AUT,4,6,3
194,1936,Germany,Berlin,Japan,JPN,6,4,8
195,1936,Germany,Berlin,Netherlands,NED,6,4,7
196,1936,Germany,Berlin,Estonia,EST,2,2,3
197,1936,Germany,Berlin,Egypt,EGY,2,1,2
198,1936,Germany,Berlin,Czechoslovakia,TCH,3,5,0
199,1936,Germany,Berlin,Argentina,ARG,2,2,3
200,1936,Germany,Berlin,United States,USA,24,20,12
201,1936,Germany,Berlin,Hungary,HUN,10,1,5
202,1936,Germany,Berlin,Portugal,POR,0,0,1
203,1936,Germany,Berlin,Germany,GER,33,26,30
204,1936,Germany,Berlin,France,FRA,7,6,6
205,1936,Germany,Berlin,Sweden,SWE,6,5,9
206,1936,Germany,Berlin,Italy,ITA,8,9,5
207,1936,Germany,Berlin,Finland,FIN,7,6,6
208,1936,Germany,Berlin,South Africa,RSA,0,1,0
209,1936,Germany,Berlin,Yugoslavia,YUG,0,1,0
210,1936,Germany,Berlin,Latvia,LAT,0,1,1
211,1936,Germany,Berlin,Romania,ROU,0,1,0
212,1936,Germany,Berlin,Australia,AUS,0,0,1
213,1936,Germany,Berlin,Philippines,PHI,0,0,1
214,1936,Germany,Berlin,Mexico,MEX,0,0,3
215,1936,Germany,Berlin,Belgium,BEL,0,0,2
216,1936,Germany,Berlin,Norway,NOR,1,3,2
217,1936,Germany,Berlin,Turkey,TUR,1,0,1
218,1936,Germany,Berlin,Switzerland,SUI,1,9,5
219,1936,Germany,Berlin,Canada,CAN,1,3,5
220,1936,Germany,Berlin,Poland,POL,0,3,3
221,1936,Germany,Berlin,Denmark,DEN,0,2,3
222,1936,Germany,Berlin,India,IND,1,0,0
223,1936,Germany,Berlin,New Zealand,NZL,1,0,0
224,1948,Great Britain,London,Belgium,BEL,2,2,3
225,1948,Great Britain,London,Mexico,MEX,2,1,2
226,1948,Great Britain,London,Australia,AUS,2,6,5
227,1948,Great Britain,London,Great Britain,GBR,3,14,6
228,1948,Great Britain,London,Argentina,ARG,3,3,1
229,1948,Great Britain,London,Austria,AUT,1,0,3
230,1948,Great Britain,London,India,IND,1,0,0
231,1948,Great Britain,London,Jamaica,JAM,1,2,0
232,1948,Great Britain,London,South Africa,RSA,2,1,1
233,1948,Great Britain,London,Norway,NOR,1,3,3
234,1948,Great Britain,London,Netherlands,NED,5,2,9
235,1948,Great Britain,London,Hungary,HUN,10,5,12
236,1948,Great Britain,London,France,FRA,10,6,13
237,1948,Great Britain,London,Italy,ITA,8,11,8
238,1948,Great Britain,London,Turkey,TUR,6,4,2
239,1948,Great Britain,London,Finland,FIN,8,7,5
240,1948,Great Britain,London,Switzerland,SUI,5,10,5
241,1948,Great Britain,London,Denmark,DEN,5,7,8
242,1948,Great Britain,London,Czechoslovakia,TCH,6,2,3
243,1948,Great Britain,London,Sweden,SWE,16,11,17
244,1948,Great Britain,London,United States,USA,38,27,19
245,1948,Great Britain,London,Peru,PER,1,0,0
246,1948,Great Britain,London,South Korea,KOR,0,0,2
247,1948,Great Britain,London,Brazil,BRA,0,0,1
248,1948,Great Britain,London,Trinidad and Tobago,TRI,0,1,0
249,1948,Great Britain,London,Panama,PAN,0,0,2
250,1948,Great Britain,London,Puerto Rico,PUR,0,0,1
251,1948,Great Britain,London,Egypt,EGY,2,2,1
252,1948,Great Britain,London,Iran,IRI,0,0,1
253,1948,Great Britain,London,Poland,POL,0,0,1
254,1948,Great Britain,London,Portugal,POR,0,1,1
255,1948,Great Britain,London,Uruguay,URU,0,1,1
256,1948,Great Britain,London,Yugoslavia,YUG,0,2,0
257,1948,Great Britain,London,Canada,CAN,0,1,2
258,1948,Great Britain,London,Spain,ESP,0,1,0
259,1948,Great Britain,London,Cuba,CUB,0,1,0
260,1948,Great Britain,London,Ceylon,CEY,0,1,0
261,1952,Finland,Helsinki,Soviet Union,URS,22,30,19
262,1952,Finland,Helsinki,Italy,ITA,8,9,4
263,1952,Finland,Helsinki,United States,USA,40,19,17
264,1952,Finland,Helsinki,Hungary,HUN,16,10,16
265,1952,Finland,Helsinki,France,FRA,6,6,6
266,1952,Finland,Helsinki,Czechoslovakia,TCH,7,3,3
267,1952,Finland,Helsinki,Sweden,SWE,12,13,10
268,1952,Finland,Helsinki,Argentina,ARG,1,2,2
269,1952,Finland,Helsinki,Poland,POL,1,2,1
270,1952,Finland,Helsinki,Japan,JPN,1,6,2
271,1952,Finland,Helsinki,Great Britain,GBR,1,2,8
272,1952,Finland,Helsinki,Canada,CAN,1,2,0
273,1952,Finland,Helsinki,Brazil,BRA,1,0,2
274,1952,Finland,Helsinki,New Zealand,NZL,1,0,2
275,1952,Finland,Helsinki,Yugoslavia,YUG,1,2,0
276,1952,Finland,Helsinki,Romania,ROU,1,1,2
277,1952,Finland,Helsinki,Norway,NOR,3,2,0
278,1952,Finland,Helsinki,Switzerland,SUI,2,6,6
279,1952,Finland,Helsinki,Finland,FIN,6,3,13
280,1952,Finland,Helsinki,Australia,AUS,6,2,3
281,1952,Finland,Helsinki,South Africa,RSA,2,4,4
282,1952,Finland,Helsinki,Denmark,DEN,2,1,3
283,1952,Finland,Helsinki,Turkey,TUR,2,0,1
284,1952,Finland,Helsinki,Jamaica,JAM,2,3,0
285,1952,Finland,Helsinki,Belgium,BEL,2,2,0
286,1952,Finland,Helsinki,South Korea,KOR,0,0,2
287,1952,Finland,Helsinki,Trinidad and Tobago,TRI,0,0,2
288,1952,Finland,Helsinki,Mexico,MEX,0,1,0
289,1952,Finland,Helsinki,Spain,ESP,0,1,0
290,1952,Finland,Helsinki,Uruguay,URU,0,0,2
291,1952,Finland,Helsinki,Portugal,POR,0,0,1
292,1952,Finland,Helsinki,Venezuela,VEN,0,0,1
293,1952,Finland,Helsinki,Bulgaria,BUL,0,0,1
294,1952,Finland,Helsinki,Egypt,EGY,0,0,1
295,1952,Finland,Helsinki,Germany,GER,0,7,17
296,1952,Finland,Helsinki,Netherlands,NED,0,5,0
297,1952,Finland,Helsinki,India,IND,1,0,1
298,1952,Finland,Helsinki,Luxembourg,LUX,1,0,0
299,1952,Finland,Helsinki,Iran,IRI,0,3,4
300,1952,Finland,Helsinki,Lebanon,LIB,0,1,1
301,1952,Finland,Helsinki,Ireland,IRL,0,1,0
302,1952,Finland,Helsinki,Chile,CHI,0,2,0
303,1952,Finland,Helsinki,Austria,AUT,0,1,1
304,1956,Australia/Sweden,Melbourne/Stockholm,Ireland,IRL,1,1,3
305,1956,Australia/Sweden,Melbourne/Stockholm,Denmark,DEN,1,2,1
306,1956,Australia/Sweden,Melbourne/Stockholm,Bulgaria,BUL,1,3,1
307,1956,Australia/Sweden,Melbourne/Stockholm,Brazil,BRA,1,0,0
308,1956,Australia/Sweden,Melbourne/Stockholm,Mexico,MEX,1,0,1
309,1956,Australia/Sweden,Melbourne/Stockholm,Norway,NOR,1,0,2
310,1956,Australia/Sweden,Melbourne/Stockholm,Canada,CAN,2,1,3
311,1956,Australia/Sweden,Melbourne/Stockholm,Iran,IRI,2,2,1
312,1956,Australia/Sweden,Melbourne/Stockholm,Bahamas,BAH,0,0,1
313,1956,Australia/Sweden,Melbourne/Stockholm,Czechoslovakia,TCH,1,4,1
314,1956,Australia/Sweden,Melbourne/Stockholm,Poland,POL,1,4,4
315,1956,Australia/Sweden,Melbourne/Stockholm,New Zealand,NZL,2,0,0
316,1956,Australia/Sweden,Melbourne/Stockholm,India,IND,1,0,0
317,1956,Australia/Sweden,Melbourne/Stockholm,Austria,AUT,0,0,2
318,1956,Australia/Sweden,Melbourne/Stockholm,South Africa,RSA,0,0,4
319,1956,Australia/Sweden,Melbourne/Stockholm,Pakistan,PAK,0,1,0
320,1956,Australia/Sweden,Melbourne/Stockholm,Uruguay,URU,0,0,1
321,1956,Australia/Sweden,Melbourne/Stockholm,Switzerland,SUI,0,0,1
322,1956,Australia/Sweden,Melbourne/Stockholm,Greece,GRE,0,0,1
323,1956,Australia/Sweden,Melbourne/Stockholm,Belgium,BEL,0,2,0
324,1956,Australia/Sweden,Melbourne/Stockholm,Chile,CHI,0,2,2
325,1956,Australia/Sweden,Melbourne/Stockholm,Yugoslavia,YUG,0,3,0
326,1956,Australia/Sweden,Melbourne/Stockholm,Iceland,ISL,0,1,0
327,1956,Australia/Sweden,Melbourne/Stockholm,South Korea,KOR,0,1,1
328,1956,Australia/Sweden,Melbourne/Stockholm,Argentina,ARG,0,1,1
329,1956,Australia/Sweden,Melbourne/Stockholm,Romania,ROU,5,3,5
330,1956,Australia/Sweden,Melbourne/Stockholm,Great Britain,GBR,6,7,11
331,1956,Australia/Sweden,Melbourne/Stockholm,United Team of Germany,EUA,6,13,7
332,1956,Australia/Sweden,Melbourne/Stockholm,Finland,FIN,3,1,11
333,1956,Australia/Sweden,Melbourne/Stockholm,Turkey,TUR,3,2,2
334,1956,Australia/Sweden,Melbourne/Stockholm,Japan,JPN,4,10,5
335,1956,Australia/Sweden,Melbourne/Stockholm,Sweden,SWE,8,5,6
336,1956,Australia/Sweden,Melbourne/Stockholm,United States,USA,32,25,17
337,1956,Australia/Sweden,Melbourne/Stockholm,Soviet Union,URS,37,29,32
338,1956,Australia/Sweden,Melbourne/Stockholm,France,FRA,4,4,6
339,1956,Australia/Sweden,Melbourne/Stockholm,Hungary,HUN,9,10,7
340,1956,Australia/Sweden,Melbourne/Stockholm,Italy,ITA,8,8,9
341,1956,Australia/Sweden,Melbourne/Stockholm,Australia,AUS,13,8,14
342,1960,Italy,Rome,Sweden,SWE,1,2,3
343,1960,Italy,Rome,Finland,FIN,1,1,3
344,1960,Italy,Rome,New Zealand,NZL,2,0,1
345,1960,Italy,Rome,Great Britain,GBR,2,6,12
346,1960,Italy,Rome,Denmark,DEN,2,3,1
347,1960,Italy,Rome,Austria,AUT,1,1,0
348,1960,Italy,Rome,Greece,GRE,1,0,0
349,1960,Italy,Rome,Norway,NOR,1,0,0
350,1960,Italy,Rome,Ethiopia,ETH,1,0,0
351,1960,Italy,Rome,Yugoslavia,YUG,1,1,0
352,1960,Italy,Rome,Pakistan,PAK,1,0,1
353,1960,Italy,Rome,United Team of Germany,EUA,12,19,11
354,1960,Italy,Rome,Australia,AUS,8,8,6
355,1960,Italy,Rome,Italy,ITA,13,10,13
356,1960,Italy,Rome,Soviet Union,URS,43,29,31
357,1960,Italy,Rome,United States,USA,34,21,16
358,1960,Italy,Rome,Turkey,TUR,7,2,0
359,1960,Italy,Rome,Czechoslovakia,TCH,3,2,3
360,1960,Italy,Rome,Romania,ROU,3,1,6
361,1960,Italy,Rome,Poland,POL,4,6,11
362,1960,Italy,Rome,Hungary,HUN,6,8,7
363,1960,Italy,Rome,Japan,JPN,4,7,7
364,1960,Italy,Rome,Singapore,SIN,0,1,0
365,1960,Italy,Rome,Brazil,BRA,0,0,2
366,1960,Italy,Rome,Republic of China,ROC,0,1,0
367,1960,Italy,Rome,Morocco,MAR,0,1,0
368,1960,Italy,Rome,Portugal,POR,0,1,0
369,1960,Italy,Rome,British West Indies,BWI,0,0,2
370,1960,Italy,Rome,Venezuela,VEN,0,0,1
371,1960,Italy,Rome,Bulgaria,BUL,1,3,3
372,1960,Italy,Rome,Spain,ESP,0,0,1
373,1960,Italy,Rome,Iraq,IRQ,0,0,1
374,1960,Italy,Rome,Mexico,MEX,0,0,1
375,1960,Italy,Rome,India,IND,0,1,0
376,1960,Italy,Rome,Iran,IRI,0,1,3
377,1960,Italy,Rome,Netherlands,NED,0,1,2
378,1960,Italy,Rome,Belgium,BEL,0,2,2
379,1960,Italy,Rome,Switzerland,SUI,0,3,3
380,1960,Italy,Rome,France,FRA,0,2,3
381,1960,Italy,Rome,South Africa,RSA,0,1,2
382,1960,Italy,Rome,Canada,CAN,0,1,0
383,1960,Italy,Rome,Ghana,GHA,0,1,0
384,1960,Italy,Rome,Egypt,EGY,0,1,1
385,1960,Italy,Rome,Argentina,ARG,0,1,1
386,1964,Japan,Tokyo,France,FRA,1,8,6
387,1964,Japan,Tokyo,Canada,CAN,1,2,1
388,1964,Japan,Tokyo,Yugoslavia,YUG,2,1,2
389,1964,Japan,Tokyo,Belgium,BEL,2,0,1
390,1964,Japan,Tokyo,Ethiopia,ETH,1,0,0
391,1964,Japan,Tokyo,India,IND,1,0,0
392,1964,Japan,Tokyo,Switzerland,SUI,1,2,1
393,1964,Japan,Tokyo,Bahamas,BAH,1,0,0
394,1964,Japan,Tokyo,New Zealand,NZL,3,0,2
395,1964,Japan,Tokyo,Romania,ROU,2,4,6
396,1964,Japan,Tokyo,Bulgaria,BUL,3,5,2
397,1964,Japan,Tokyo,Finland,FIN,3,0,2
398,1964,Japan,Tokyo,Sweden,SWE,2,2,4
399,1964,Japan,Tokyo,Denmark,DEN,2,1,3
400,1964,Japan,Tokyo,Netherlands,NED,2,4,4
401,1964,Japan,Tokyo,Turkey,TUR,2,3,1
402,1964,Japan,Tokyo,Ireland,IRL,0,0,1
403,1964,Japan,Tokyo,Kenya,KEN,0,0,1
404,1964,Japan,Tokyo,Brazil,BRA,0,0,1
405,1964,Japan,Tokyo,Ghana,GHA,0,0,1
406,1964,Japan,Tokyo,Uruguay,URU,0,0,1
407,1964,Japan,Tokyo,Japan,JPN,16,5,8
408,1964,Japan,Tokyo,Mexico,MEX,0,0,1
409,1964,Japan,Tokyo,Nigeria,NGR,0,0,1
410,1964,Japan,Tokyo,Tunisia,TUN,0,1,1
411,1964,Japan,Tokyo,Argentina,ARG,0,1,0
412,1964,Japan,Tokyo,South Korea,KOR,0,2,1
413,1964,Japan,Tokyo,Trinidad and Tobago,TRI,0,1,2
414,1964,Japan,Tokyo,Philippines,PHI,0,1,0
415,1964,Japan,Tokyo,Iran,IRI,0,0,2
416,1964,Japan,Tokyo,Cuba,CUB,0,1,0
417,1964,Japan,Tokyo,Pakistan,PAK,0,1,0
418,1964,Japan,Tokyo,United Team of Germany,EUA,10,22,18
419,1964,Japan,Tokyo,Italy,ITA,10,10,7
420,1964,Japan,Tokyo,United States,USA,36,26,28
421,1964,Japan,Tokyo,Soviet Union,URS,30,31,35
422,1964,Japan,Tokyo,Hungary,HUN,10,7,5
423,1964,Japan,Tokyo,Czechoslovakia,TCH,5,6,3

### Creating the new column 'Total Medals'

In [ ]:
c.execute('''
ALTER TABLE olympic_medals
ADD COLUMN 'Total_Medals' INT;
''')

In [ ]:
c.execute('''
UPDATE olympic_medals
SET Total_Medals = Gold + Silver + Bronze;
''')
conn.commit()

In [ ]:
# Let's check our results
query_check = '''
SELECT * FROM olympic_medals
'''
pd.read_sql_query(query_check, conn)
# Everything seems okay

,Year,Host_country,Host_city,Country_Name,Country_Code,Gold,Silver,Bronze,Total_Medals
0,1896,Greece,Athens,Great Britain,GBR,2,3,2,7
1,1896,Greece,Athens,Hungary,HUN,2,1,3,6
2,1896,Greece,Athens,France,FRA,5,4,2,11
3,1896,Greece,Athens,United States,USA,11,7,2,20
4,1896,Greece,Athens,Germany,GER,6,5,2,13
5,1896,Greece,Athens,Austria,AUT,2,1,2,5
6,1896,Greece,Athens,Mixed team,ZZX,1,0,1,2
7,1896,Greece,Athens,Greece,GRE,10,18,19,47
8,1896,Greece,Athens,Switzerland,SUI,1,2,0,3
9,1896,Greece,Athens,Australia,AUS,2,0,0,2
10,1896,Greece,Athens,Denmark,DEN,1,2,3,6
11,1900,France,Paris,Italy,ITA,3,2,0,5
12,1900,France,Paris,Germany,GER,4,3,2,9
13,1900,France,Paris,Australia,AUS,2,0,3,5
14,1900,France,Paris,Hungary,HUN,1,2,2,5
15,1900,France,Paris,Denmark,DEN,1,3,2,6
16,1900,France,Paris,France,FRA,27,38,37,102
17,1900,France,Paris,Switzerland,SUI,6,2,1,9
18,1900,France,Paris,United States,USA,19,14,15,48
19,1900,France,Paris,Mixed team,ZZX,8,5,6,19
20,1900,France,Paris,Great Britain,GBR,15,8,9,32
21,1900,France,Paris,Cuba,CUB,1,1,0,2
22,1900,France,Paris,India,IND,0,2,0,2
23,1900,France,Paris,Netherlands,NED,0,2,3,5
24,1900,France,Paris,Bohemia,BOH,0,1,1,2
25,1900,France,Paris,Belgium,BEL,6,7,4,17
26,1900,France,Paris,Sweden,SWE,0,0,1,1
27,1900,France,Paris,Spain,ESP,1,0,0,1
28,1900,France,Paris,Canada,CAN,1,0,1,2
29,1900,France,Paris,Luxembourg,LUX,1,0,0,1
30,1900,France,Paris,Norway,NOR,0,2,3,5
31,1900,France,Paris,Austria,AUT,0,3,3,6
32,1904,United States,St. Louis,Cuba,CUB,3,0,0,3
33,1904,United States,St. Louis,Hungary,HUN,2,1,1,4
34,1904,United States,St. Louis,Mixed team,ZZX,2,1,1,4
35,1904,United States,St. Louis,United States,USA,76,78,77,231
36,1904,United States,St. Louis,Germany,GER,4,5,6,15
37,1904,United States,St. Louis,Canada,CAN,4,1,1,6
38,1904,United States,St. Louis,Greece,GRE,1,0,1,2
39,1904,United States,St. Louis,Australia,AUS,0,3,1,4
40,1904,United States,St. Louis,France,FRA,0,1,0,1
41,1904,United States,St. Louis,Switzerland,SUI,1,0,2,3
42,1904,United States,St. Louis,Norway,NOR,2,0,0,2
43,1904,United States,St. Louis,Austria,AUT,1,1,1,3
44,1904,United States,St. Louis,Great Britain,GBR,1,1,0,2
45,1908,Great Britain,London,Canada,CAN,3,3,10,16
46,1908,Great Britain,London,Hungary,HUN,3,4,2,9
47,1908,Great Britain,London,Italy,ITA,2,2,0,4
48,1908,Great Britain,London,Norway,NOR,2,3,3,8
49,1908,Great Britain,London,Germany,GER,3,5,5,13
50,1908,Great Britain,London,United States,USA,23,12,12,47
51,1908,Great Britain,London,Great Britain,GBR,56,51,39,146
52,1908,Great Britain,London,France,FRA,5,5,9,19
53,1908,Great Britain,London,Sweden,SWE,8,6,11,25
54,1908,Great Britain,London,Denmark,DEN,0,2,3,5
55,1908,Great Britain,London,Greece,GRE,0,3,1,4
56,1908,Great Britain,London,Bohemia,BOH,0,0,2,2
57,1908,Great Britain,London,Austria,AUT,0,0,1,1
58,1908,Great Britain,London,Netherlands,NED,0,0,2,2
59,1908,Great Britain,London,Australasia,ANZ,1,2,2,5
60,1908,Great Britain,London,Belgium,BEL,1,5,2,8
61,1908,Great Britain,London,Russian Empire,RU1,1,2,0,3
62,1908,Great Britain,London,South Africa,RSA,1,1,0,2
63,1908,Great Britain,London,Finland,FIN,1,1,3,5
64,1912,Sweden,Stockholm,Germany,GER,6,13,7,26
65,1912,Sweden,Stockholm,Italy,ITA,5,1,2,8
66,1912,Sweden,Stockholm,Norway,NOR,4,1,5,10
67,1912,Sweden,Stockholm,South Africa,RSA,4,2,0,6
68,1912,Sweden,Stockholm,Sweden,SWE,24,24,17,65
69,1912,Sweden,Stockholm,United States,USA,26,19,19,64
70,1912,Sweden,Stockholm,France,FRA,7,5,3,15
71,1912,Sweden,Stockholm,Finland,FIN,9,8,9,26
72,1912,Sweden,Stockholm,Canada,CAN,3,2,3,8
73,1912,Sweden,Stockholm,Russian Empire,RU1,0,2,3,5
74,1912,Sweden,Stockholm,Switzerland,SUI,1,0,0,1
75,1912,Sweden,Stockholm,Netherlands,NED,0,0,3,3
76,1912,Sweden,Stockholm,Austria,AUT,0,2,2,4
77,1912,Sweden,Stockholm,Greece,GRE,1,0,1,2
78,1912,Sweden,Stockholm,Australasia,ANZ,2,2,3,7
79,1912,Sweden,Stockholm,Hungary,HUN,3,2,3,8
80,1912,Sweden,Stockholm,Denmark,DEN,1,6,5,12
81,1912,Sweden,Stockholm,Belgium,BEL,2,1,3,6
82,1912,Sweden,Stockholm,Great Britain,GBR,10,15,16,41
83,1920,Belgium,Antwerp,Switzerland,SUI,2,2,7,11
84,1920,Belgium,Antwerp,Brazil,BRA,1,1,1,3
85,1920,Belgium,Antwerp,Australia,AUS,0,2,1,3
86,1920,Belgium,Antwerp,Denmark,DEN,3,9,1,13
87,1920,Belgium,Antwerp,South Africa,RSA,3,4,3,10
88,1920,Belgium,Antwerp,Canada,CAN,3,3,3,9
89,1920,Belgium,Antwerp,Luxembourg,LUX,0,1,0,1
90,1920,Belgium,Antwerp,Czechoslovakia,TCH,0,0,2,2
91,1920,Belgium,Antwerp,New Zealand,NZL,0,0,1,1
92,1920,Belgium,Antwerp,Japan,JPN,0,2,0,2
93,1920,Belgium,Antwerp,Spain,ESP,0,2,0,2
94,1920,Belgium,Antwerp,Greece,GRE,0,1,0,1
95,1920,Belgium,Antwerp,Netherlands,NED,4,2,5,11
96,1920,Belgium,Antwerp,Belgium,BEL,16,12,14,42
97,1920,Belgium,Antwerp,Finland,FIN,15,10,9,34
98,1920,Belgium,Antwerp,Sweden,SWE,19,20,25,64
99,1920,Belgium,Antwerp,Estonia,EST,1,2,0,3
100,1920,Belgium,Antwerp,United States,USA,41,27,27,95
101,1920,Belgium,Antwerp,France,FRA,9,19,13,41
102,1920,Belgium,Antwerp,Italy,ITA,13,5,5,23
103,1920,Belgium,Antwerp,Norway,NOR,13,9,9,31
104,1920,Belgium,Antwerp,Great Britain,GBR,14,16,13,43
105,1924,France,Paris,Norway,NOR,5,2,3,10
106,1924,France,Paris,Sweden,SWE,4,13,12,29
107,1924,France,Paris,Denmark,DEN,2,5,2,9
108,1924,France,Paris,Netherlands,NED,4,1,5,10
109,1924,France,Paris,Belgium,BEL,3,7,3,13
110,1924,France,Paris,Australia,AUS,3,1,2,6
111,1924,France,Paris,Switzerland,SUI,7,8,10,25
112,1924,France,Paris,France,FRA,13,15,10,38
113,1924,France,Paris,Finland,FIN,14,13,10,37
114,1924,France,Paris,United States,USA,45,27,27,99
115,1924,France,Paris,Italy,ITA,8,3,5,16
116,1924,France,Paris,Great Britain,GBR,9,13,12,34
117,1924,France,Paris,Haiti,HAI,0,0,1,1
118,1924,France,Paris,Hungary,HUN,2,3,4,9
119,1924,France,Paris,Romania,ROU,0,0,1,1
120,1924,France,Paris,Poland,POL,0,1,1,2
121,1924,France,Paris,Canada,CAN,0,3,1,4
122,1924,France,Paris,Japan,JPN,0,0,1,1
123,1924,France,Paris,New Zealand,NZL,0,0,1,1
124,1924,France,Paris,Portugal,POR,0,0,1,1
125,1924,France,Paris,Austria,AUT,0,3,1,4
126,1924,France,Paris,Argentina,ARG,1,3,2,6
127,1924,France,Paris,Czechoslovakia,TCH,1,4,5,10
128,1924,France,Paris,Yugoslavia,YUG,2,0,0,2
129,1924,France,Paris,Uruguay,URU,1,0,0,1
130,1924,France,Paris,South Africa,RSA,1,1,1,3
131,1924,France,Paris,Estonia,EST,1,1,4,6
132,1928,Netherlands,Amsterdam,Great Britain,GBR,3,10,7,20
133,1928,Netherlands,Amsterdam,Canada,CAN,4,4,7,15
134,1928,Netherlands,Amsterdam,Hungary,HUN,4,5,0,9
135,1928,Netherlands,Amsterdam,Czechoslovakia,TCH,2,5,2,9
136,1928,Netherlands,Amsterdam,Japan,JPN,2,2,1,5
137,1928,Netherlands,Amsterdam,Argentina,ARG,3,3,1,7
138,1928,Netherlands,Amsterdam,Denmark,DEN,3,1,2,6
139,1928,Netherlands,Amsterdam,Netherlands,NED,6,9,4,19
140,1928,Netherlands,Amsterdam,Germany,GER,10,7,14,31
141,1928,Netherlands,Amsterdam,Finland,FIN,8,8,9,25
142,1928,Netherlands,Amsterdam,South Africa,RSA,1,0,2,3
143,1928,Netherlands,Amsterdam,United States,USA,22,18,16,56
144,1928,Netherlands,Amsterdam,Switzerland,SUI,7,4,4,15
145,1928,Netherlands,Amsterdam,France,FRA,6,10,5,21
146,1928,Netherlands,Amsterdam,Sweden,SWE,7,6,12,25
147,1928,Netherlands,Amsterdam,Italy,ITA,7,5,7,19
148,1928,Netherlands,Amsterdam,Estonia,EST,2,1,2,5
149,1928,Netherlands,Amsterdam,Uruguay,URU,1,0,0,1
150,1928,Netherlands,Amsterdam,Belgium,BEL,0,1,2,3
151,1928,Netherlands,Amsterdam,New Zealand,NZL,1,0,0,1
152,1928,Netherlands,Amsterdam,Spain,ESP,1,0,0,1
153,1928,Netherlands,Amsterdam,Philippines,PHI,0,0,1,1
154,1928,Netherlands,Amsterdam,Portugal,POR,0,0,1,1
155,1928,Netherlands,Amsterdam,Chile,CHI,0,1,0,1
156,1928,Netherlands,Amsterdam,Haiti,HAI,0,1,0,1
157,1928,Netherlands,Amsterdam,Australia,AUS,1,2,1,4
158,1928,Netherlands,Amsterdam,Norway,NOR,1,2,1,4
159,1928,Netherlands,Amsterdam,Egypt,EGY,2,1,1,4
160,1928,Netherlands,Amsterdam,Austria,AUT,2,0,1,3
161,1928,Netherlands,Amsterdam,India,IND,1,0,0,1
162,1928,Netherlands,Amsterdam,Ireland,IRL,1,0,0,1
163,1928,Netherlands,Amsterdam,Poland,POL,1,1,3,5
164,1928,Netherlands,Amsterdam,Yugoslavia,YUG,1,1,3,5
165,1932,United States,Los Angeles,Argentina,ARG,3,1,0,4
166,1932,United States,Los Angeles,Australia,AUS,3,1,1,5
167,1932,United States,Los Angeles,Germany,GER,3,12,5,20
168,1932,United States,Los Angeles,Poland,POL,2,1,4,7
169,1932,United States,Los Angeles,Netherlands,NED,2,5,0,7
170,1932,United States,Los Angeles,Canada,CAN,2,5,8,15
171,1932,United States,Los Angeles,Great Britain,GBR,4,7,5,16
172,1932,United States,Los Angeles,Sweden,SWE,9,5,9,23
173,1932,United States,Los Angeles,France,FRA,10,5,4,19
174,1932,United States,Los Angeles,Italy,ITA,12,12,12,36
175,1932,United States,Los Angeles,Finland,FIN,5,8,12,25
176,1932,United States,Los Angeles,Hungary,HUN,6,4,5,15
177,1932,United States,Los Angeles,Japan,JPN,7,7,4,18
178,1932,United States,Los Angeles,South Africa,RSA,2,0,3,5
179,1932,United States,Los Angeles,Philippines,PHI,0,0,3,3
180,1932,United States,Los Angeles,Switzerland,SUI,0,1,0,1
181,1932,United States,Los Angeles,New Zealand,NZL,0,1,0,1
182,1932,United States,Los Angeles,United States,USA,41,32,30,103
183,1932,United States,Los Angeles,Uruguay,URU,0,0,1,1
184,1932,United States,Los Angeles,Spain,ESP,0,0,1,1
185,1932,United States,Los Angeles,Latvia,LAT,0,1,0,1
186,1932,United States,Los Angeles,Austria,AUT,1,1,3,5
187,1932,United States,Los Angeles,Czechoslovakia,TCH,1,2,1,4
188,1932,United States,Los Angeles,Ireland,IRL,2,0,0,2
189,1932,United States,Los Angeles,Mexico,MEX,0,2,0,2
190,1932,United States,Los Angeles,Denmark,DEN,0,3,3,6
191,1932,United States,Los Angeles,India,IND,1,0,0,1
192,1936,Germany,Berlin,Great Britain,GBR,4,7,3,14
193,1936,Germany,Berlin,Austria,AUT,4,6,3,13
194,1936,Germany,Berlin,Japan,JPN,6,4,8,18
195,1936,Germany,Berlin,Netherlands,NED,6,4,7,17
196,1936,Germany,Berlin,Estonia,EST,2,2,3,7
197,1936,Germany,Berlin,Egypt,EGY,2,1,2,5
198,1936,Germany,Berlin,Czechoslovakia,TCH,3,5,0,8
199,1936,Germany,Berlin,Argentina,ARG,2,2,3,7
200,1936,Germany,Berlin,United States,USA,24,20,12,56
201,1936,Germany,Berlin,Hungary,HUN,10,1,5,16
202,1936,Germany,Berlin,Portugal,POR,0,0,1,1
203,1936,Germany,Berlin,Germany,GER,33,26,30,89
204,1936,Germany,Berlin,France,FRA,7,6,6,19
205,1936,Germany,Berlin,Sweden,SWE,6,5,9,20
206,1936,Germany,Berlin,Italy,ITA,8,9,5,22
207,1936,Germany,Berlin,Finland,FIN,7,6,6,19
208,1936,Germany,Berlin,South Africa,RSA,0,1,0,1
209,1936,Germany,Berlin,Yugoslavia,YUG,0,1,0,1
210,1936,Germany,Berlin,Latvia,LAT,0,1,1,2
211,1936,Germany,Berlin,Romania,ROU,0,1,0,1
212,1936,Germany,Berlin,Australia,AUS,0,0,1,1
213,1936,Germany,Berlin,Philippines,PHI,0,0,1,1
214,1936,Germany,Berlin,Mexico,MEX,0,0,3,3
215,1936,Germany,Berlin,Belgium,BEL,0,0,2,2
216,1936,Germany,Berlin,Norway,NOR,1,3,2,6
217,1936,Germany,Berlin,Turkey,TUR,1,0,1,2
218,1936,Germany,Berlin,Switzerland,SUI,1,9,5,15
219,1936,Germany,Berlin,Canada,CAN,1,3,5,9
220,1936,Germany,Berlin,Poland,POL,0,3,3,6
221,1936,Germany,Berlin,Denmark,DEN,0,2,3,5
222,1936,Germany,Berlin,India,IND,1,0,0,1
223,1936,Germany,Berlin,New Zealand,NZL,1,0,0,1
224,1948,Great Britain,London,Belgium,BEL,2,2,3,7
225,1948,Great Britain,London,Mexico,MEX,2,1,2,5
226,1948,Great Britain,London,Australia,AUS,2,6,5,13
227,1948,Great Britain,London,Great Britain,GBR,3,14,6,23
228,1948,Great Britain,London,Argentina,ARG,3,3,1,7
229,1948,Great Britain,London,Austria,AUT,1,0,3,4
230,1948,Great Britain,London,India,IND,1,0,0,1
231,1948,Great Britain,London,Jamaica,JAM,1,2,0,3
232,1948,Great Britain,London,South Africa,RSA,2,1,1,4
233,1948,Great Britain,London,Norway,NOR,1,3,3,7
234,1948,Great Britain,London,Netherlands,NED,5,2,9,16
235,1948,Great Britain,London,Hungary,HUN,10,5,12,27
236,1948,Great Britain,London,France,FRA,10,6,13,29
237,1948,Great Britain,London,Italy,ITA,8,11,8,27
238,1948,Great Britain,London,Turkey,TUR,6,4,2,12
239,1948,Great Britain,London,Finland,FIN,8,7,5,20
240,1948,Great Britain,London,Switzerland,SUI,5,10,5,20
241,1948,Great Britain,London,Denmark,DEN,5,7,8,20
242,1948,Great Britain,London,Czechoslovakia,TCH,6,2,3,11
243,1948,Great Britain,London,Sweden,SWE,16,11,17,44
244,1948,Great Britain,London,United States,USA,38,27,19,84
245,1948,Great Britain,London,Peru,PER,1,0,0,1
246,1948,Great Britain,London,South Korea,KOR,0,0,2,2
247,1948,Great Britain,London,Brazil,BRA,0,0,1,1
248,1948,Great Britain,London,Trinidad and Tobago,TRI,0,1,0,1
249,1948,Great Britain,London,Panama,PAN,0,0,2,2
250,1948,Great Britain,London,Puerto Rico,PUR,0,0,1,1
251,1948,Great Britain,London,Egypt,EGY,2,2,1,5
252,1948,Great Britain,London,Iran,IRI,0,0,1,1
253,1948,Great Britain,London,Poland,POL,0,0,1,1
254,1948,Great Britain,London,Portugal,POR,0,1,1,2
255,1948,Great Britain,London,Uruguay,URU,0,1,1,2
256,1948,Great Britain,London,Yugoslavia,YUG,0,2,0,2
257,1948,Great Britain,London,Canada,CAN,0,1,2,3
258,1948,Great Britain,London,Spain,ESP,0,1,0,1
259,1948,Great Britain,London,Cuba,CUB,0,1,0,1
260,1948,Great Britain,London,Ceylon,CEY,0,1,0,1
261,1952,Finland,Helsinki,Soviet Union,URS,22,30,19,71
262,1952,Finland,Helsinki,Italy,ITA,8,9,4,21
263,1952,Finland,Helsinki,United States,USA,40,19,17,76
264,1952,Finland,Helsinki,Hungary,HUN,16,10,16,42
265,1952,Finland,Helsinki,France,FRA,6,6,6,18
266,1952,Finland,Helsinki,Czechoslovakia,TCH,7,3,3,13
267,1952,Finland,Helsinki,Sweden,SWE,12,13,10,35
268,1952,Finland,Helsinki,Argentina,ARG,1,2,2,5
269,1952,Finland,Helsinki,Poland,POL,1,2,1,4
270,1952,Finland,Helsinki,Japan,JPN,1,6,2,9
271,1952,Finland,Helsinki,Great Britain,GBR,1,2,8,11
272,1952,Finland,Helsinki,Canada,CAN,1,2,0,3
273,1952,Finland,Helsinki,Brazil,BRA,1,0,2,3
274,1952,Finland,Helsinki,New Zealand,NZL,1,0,2,3
275,1952,Finland,Helsinki,Yugoslavia,YUG,1,2,0,3
276,1952,Finland,Helsinki,Romania,ROU,1,1,2,4
277,1952,Finland,Helsinki,Norway,NOR,3,2,0,5
278,1952,Finland,Helsinki,Switzerland,SUI,2,6,6,14
279,1952,Finland,Helsinki,Finland,FIN,6,3,13,22
280,1952,Finland,Helsinki,Australia,AUS,6,2,3,11
281,1952,Finland,Helsinki,South Africa,RSA,2,4,4,10
282,1952,Finland,Helsinki,Denmark,DEN,2,1,3,6
283,1952,Finland,Helsinki,Turkey,TUR,2,0,1,3
284,1952,Finland,Helsinki,Jamaica,JAM,2,3,0,5
285,1952,Finland,Helsinki,Belgium,BEL,2,2,0,4
286,1952,Finland,Helsinki,South Korea,KOR,0,0,2,2
287,1952,Finland,Helsinki,Trinidad and Tobago,TRI,0,0,2,2
288,1952,Finland,Helsinki,Mexico,MEX,0,1,0,1
289,1952,Finland,Helsinki,Spain,ESP,0,1,0,1
290,1952,Finland,Helsinki,Uruguay,URU,0,0,2,2
291,1952,Finland,Helsinki,Portugal,POR,0,0,1,1
292,1952,Finland,Helsinki,Venezuela,VEN,0,0,1,1
293,1952,Finland,Helsinki,Bulgaria,BUL,0,0,1,1
294,1952,Finland,Helsinki,Egypt,EGY,0,0,1,1
295,1952,Finland,Helsinki,Germany,GER,0,7,17,24
296,1952,Finland,Helsinki,Netherlands,NED,0,5,0,5
297,1952,Finland,Helsinki,India,IND,1,0,1,2
298,1952,Finland,Helsinki,Luxembourg,LUX,1,0,0,1
299,1952,Finland,Helsinki,Iran,IRI,0,3,4,7
300,1952,Finland,Helsinki,Lebanon,LIB,0,1,1,2
301,1952,Finland,Helsinki,Ireland,IRL,0,1,0,1
302,1952,Finland,Helsinki,Chile,CHI,0,2,0,2
303,1952,Finland,Helsinki,Austria,AUT,0,1,1,2
304,1956,Australia/Sweden,Melbourne/Stockholm,Ireland,IRL,1,1,3,5
305,1956,Australia/Sweden,Melbourne/Stockholm,Denmark,DEN,1,2,1,4
306,1956,Australia/Sweden,Melbourne/Stockholm,Bulgaria,BUL,1,3,1,5
307,1956,Australia/Sweden,Melbourne/Stockholm,Brazil,BRA,1,0,0,1
308,1956,Australia/Sweden,Melbourne/Stockholm,Mexico,MEX,1,0,1,2
309,1956,Australia/Sweden,Melbourne/Stockholm,Norway,NOR,1,0,2,3
310,1956,Australia/Sweden,Melbourne/Stockholm,Canada,CAN,2,1,3,6
311,1956,Australia/Sweden,Melbourne/Stockholm,Iran,IRI,2,2,1,5
312,1956,Australia/Sweden,Melbourne/Stockholm,Bahamas,BAH,0,0,1,1
313,1956,Australia/Sweden,Melbourne/Stockholm,Czechoslovakia,TCH,1,4,1,6
314,1956,Australia/Sweden,Melbourne/Stockholm,Poland,POL,1,4,4,9
315,1956,Australia/Sweden,Melbourne/Stockholm,New Zealand,NZL,2,0,0,2
316,1956,Australia/Sweden,Melbourne/Stockholm,India,IND,1,0,0,1
317,1956,Australia/Sweden,Melbourne/Stockholm,Austria,AUT,0,0,2,2
318,1956,Australia/Sweden,Melbourne/Stockholm,South Africa,RSA,0,0,4,4
319,1956,Australia/Sweden,Melbourne/Stockholm,Pakistan,PAK,0,1,0,1
320,1956,Australia/Sweden,Melbourne/Stockholm,Uruguay,URU,0,0,1,1
321,1956,Australia/Sweden,Melbourne/Stockholm,Switzerland,SUI,0,0,1,1
322,1956,Australia/Sweden,Melbourne/Stockholm,Greece,GRE,0,0,1,1
323,1956,Australia/Sweden,Melbourne/Stockholm,Belgium,BEL,0,2,0,2
324,1956,Australia/Sweden,Melbourne/Stockholm,Chile,CHI,0,2,2,4
325,1956,Australia/Sweden,Melbourne/Stockholm,Yugoslavia,YUG,0,3,0,3
326,1956,Australia/Sweden,Melbourne/Stockholm,Iceland,ISL,0,1,0,1
327,1956,Australia/Sweden,Melbourne/Stockholm,South Korea,KOR,0,1,1,2
328,1956,Australia/Sweden,Melbourne/Stockholm,Argentina,ARG,0,1,1,2
329,1956,Australia/Sweden,Melbourne/Stockholm,Romania,ROU,5,3,5,13
330,1956,Australia/Sweden,Melbourne/Stockholm,Great Britain,GBR,6,7,11,24
331,1956,Australia/Sweden,Melbourne/Stockholm,United Team of Germany,EUA,6,13,7,26
332,1956,Australia/Sweden,Melbourne/Stockholm,Finland,FIN,3,1,11,15
333,1956,Australia/Sweden,Melbourne/Stockholm,Turkey,TUR,3,2,2,7
334,1956,Australia/Sweden,Melbourne/Stockholm,Japan,JPN,4,10,5,19
335,1956,Australia/Sweden,Melbourne/Stockholm,Sweden,SWE,8,5,6,19
336,1956,Australia/Sweden,Melbourne/Stockholm,United States,USA,32,25,17,74
337,1956,Australia/Sweden,Melbourne/Stockholm,Soviet Union,URS,37,29,32,98
338,1956,Australia/Sweden,Melbourne/Stockholm,France,FRA,4,4,6,14
339,1956,Australia/Sweden,Melbourne/Stockholm,Hungary,HUN,9,10,7,26
340,1956,Australia/Sweden,Melbourne/Stockholm,Italy,ITA,8,8,9,25
341,1956,Australia/Sweden,Melbourne/Stockholm,Australia,AUS,13,8,14,35
342,1960,Italy,Rome,Sweden,SWE,1,2,3,6
343,1960,Italy,Rome,Finland,FIN,1,1,3,5
344,1960,Italy,Rome,New Zealand,NZL,2,0,1,3
345,1960,Italy,Rome,Great Britain,GBR,2,6,12,20
346,1960,Italy,Rome,Denmark,DEN,2,3,1,6
347,1960,Italy,Rome,Austria,AUT,1,1,0,2
348,1960,Italy,Rome,Greece,GRE,1,0,0,1
349,1960,Italy,Rome,Norway,NOR,1,0,0,1
350,1960,Italy,Rome,Ethiopia,ETH,1,0,0,1
351,1960,Italy,Rome,Yugoslavia,YUG,1,1,0,2
352,1960,Italy,Rome,Pakistan,PAK,1,0,1,2
353,1960,Italy,Rome,United Team of Germany,EUA,12,19,11,42
354,1960,Italy,Rome,Australia,AUS,8,8,6,22
355,1960,Italy,Rome,Italy,ITA,13,10,13,36
356,1960,Italy,Rome,Soviet Union,URS,43,29,31,103
357,1960,Italy,Rome,United States,USA,34,21,16,71
358,1960,Italy,Rome,Turkey,TUR,7,2,0,9
359,1960,Italy,Rome,Czechoslovakia,TCH,3,2,3,8
360,1960,Italy,Rome,Romania,ROU,3,1,6,10
361,1960,Italy,Rome,Poland,POL,4,6,11,21
362,1960,Italy,Rome,Hungary,HUN,6,8,7,21
363,1960,Italy,Rome,Japan,JPN,4,7,7,18
364,1960,Italy,Rome,Singapore,SIN,0,1,0,1
365,1960,Italy,Rome,Brazil,BRA,0,0,2,2
366,1960,Italy,Rome,Republic of China,ROC,0,1,0,1
367,1960,Italy,Rome,Morocco,MAR,0,1,0,1
368,1960,Italy,Rome,Portugal,POR,0,1,0,1
369,1960,Italy,Rome,British West Indies,BWI,0,0,2,2
370,1960,Italy,Rome,Venezuela,VEN,0,0,1,1
371,1960,Italy,Rome,Bulgaria,BUL,1,3,3,7
372,1960,Italy,Rome,Spain,ESP,0,0,1,1
373,1960,Italy,Rome,Iraq,IRQ,0,0,1,1
374,1960,Italy,Rome,Mexico,MEX,0,0,1,1
375,1960,Italy,Rome,India,IND,0,1,0,1
376,1960,Italy,Rome,Iran,IRI,0,1,3,4
377,1960,Italy,Rome,Netherlands,NED,0,1,2,3
378,1960,Italy,Rome,Belgium,BEL,0,2,2,4
379,1960,Italy,Rome,Switzerland,SUI,0,3,3,6
380,1960,Italy,Rome,France,FRA,0,2,3,5
381,1960,Italy,Rome,South Africa,RSA,0,1,2,3
382,1960,Italy,Rome,Canada,CAN,0,1,0,1
383,1960,Italy,Rome,Ghana,GHA,0,1,0,1
384,1960,Italy,Rome,Egypt,EGY,0,1,1,2
385,1960,Italy,Rome,Argentina,ARG,0,1,1,2
386,1964,Japan,Tokyo,France,FRA,1,8,6,15
387,1964,Japan,Tokyo,Canada,CAN,1,2,1,4
388,1964,Japan,Tokyo,Yugoslavia,YUG,2,1,2,5
389,1964,Japan,Tokyo,Belgium,BEL,2,0,1,3
390,1964,Japan,Tokyo,Ethiopia,ETH,1,0,0,1
391,1964,Japan,Tokyo,India,IND,1,0,0,1
392,1964,Japan,Tokyo,Switzerland,SUI,1,2,1,4
393,1964,Japan,Tokyo,Bahamas,BAH,1,0,0,1
394,1964,Japan,Tokyo,New Zealand,NZL,3,0,2,5
395,1964,Japan,Tokyo,Romania,ROU,2,4,6,12
396,1964,Japan,Tokyo,Bulgaria,BUL,3,5,2,10
397,1964,Japan,Tokyo,Finland,FIN,3,0,2,5
398,1964,Japan,Tokyo,Sweden,SWE,2,2,4,8
399,1964,Japan,Tokyo,Denmark,DEN,2,1,3,6
400,1964,Japan,Tokyo,Netherlands,NED,2,4,4,10

### Ranking the countries with the most medals

In [ ]:
# Let's check our results
query_rank = '''
SELECT Country_Name, SUM(Total_Medals) AS Performance
FROM olympic_medals
GROUP BY Country_Name
HAVING Performance >= 70
ORDER BY Performance DESC
LIMIT 50;
'''
pd.read_sql_query(query_rank, conn)
# The US seems to dominate with the Soviet Union and other European countries following from afar

              Country_Name  Performance
0            United States         2630
1             Soviet Union         1010
2            Great Britain          918
3                   France          752
4                  Germany          656
5                    China          634
6                    Italy          620
7                Australia          547
8                  Hungary          511
9                   Sweden          503
10                   Japan          497
11                  Russia          426
12            East Germany          409
13                  Canada          326
14             Netherlands          322
15                 Romania          308
16                 Finland          305
17                  Poland          298
18             South Korea          287
19                    Cuba          235
20                Bulgaria          224
21             Switzerland          207
22                 Denmark          205
23            West Germany          204
24                   Spain          168
25                  Norway          163
26                 Belgium          163
27                  Brazil          150
28          Czechoslovakia          143
29                 Ukraine          139
30             New Zealand          137
31                  Greece          121
32  United Team of Germany          118
33                   Kenya          113
34            Unified Team          112
35                  Turkey          104
36                 Austria           96
37              Yugoslavia           90
38            South Africa           89
39                 Jamaica           87
40                 Belarus           85
41               Argentina           77
42                    Iran           76
43                  Mexico           72
44              Kazakhstan           72
45                     ROC           71

### Ranking the countries with the most medals after the creation and before the dissolution of the Soviet Union

In [ ]:
# Let's check our results
query_rank_adjusted = '''
SELECT Country_Name, SUM(Total_Medals) AS Performance
FROM olympic_medals
WHERE Year BETWEEN 1952 AND 1991 
GROUP BY Country_Name
ORDER BY Performance DESC
LIMIT 50;
'''
pd.read_sql_query(query_rank_adjusted, conn)
# The Soviet Union and the US seem to be at the top, with East Germany being third 
# and other European countries following the formerly communist Germany close

              Country_Name  Performance
0             Soviet Union         1010
1            United States          874
2             East Germany          409
3                  Hungary          255
4                    Italy          217
5             West Germany          204
6                    Japan          200
7                  Romania          199
8            Great Britain          199
9                Australia          172
10                  Poland          170
11                Bulgaria          151
12                  France          147
13                  Sweden          135
14  United Team of Germany          118
15          Czechoslovakia           92
16                 Finland           89
17                  Canada           89
18              Yugoslavia           73
19             South Korea           68
20             Netherlands           60
21                   China           60
22             Switzerland           51
23                 Denmark           49
24             New Zealand           47
25                    Cuba           46
26                  Turkey           33
27                  Brazil           32
28                   Kenya           31
29                 Belgium           30
30                  Mexico           29
31                    Iran           29
32                  Norway           25
33                 Germany           24
34                 Austria           22
35                   Spain           20
36            South Africa           17
37                 Jamaica           17
38               Argentina           15
39             North Korea           12
40                Mongolia           11
41                  Greece           11
42                 Ireland           10
43                Ethiopia           10
44                Pakistan            9
45               Venezuela            8
46                Portugal            8
47                   India            8
48                   Chile            7
49     Trinidad and Tobago            6

In [ ]:
query_medals_per_game = '''
SELECT Country_Name, SUM(total_medals) AS medals, COUNT(total_medals) AS games,
SUM(total_medals)/COUNT(total_medals) AS medals_per_game
FROM olympic_medals
GROUP BY Country_Name
ORDER BY medals_per_game DESC
LIMIT 50;
'''
pd.read_sql_query(query_medals_per_game, conn)
# Overall the Unified Team (Team of former Soviet republics compeeting 1 year after the collapse of the USSR) has the best performance
# Other communist/formerly communist countries also have a high degree of medals per game
# The US is third with other European countries following it
# ROC (Russian athletes competing in 2022) also have a high degree of medals per game

              Country_Name  medals  games  medals_per_game
0             Unified Team     112      1              112
1             Soviet Union    1010      9              112
2            United States    2630     28               93
3             East Germany     409      5               81
4                   Russia     426      6               71
5                      ROC      71      1               71
6                    China     634     10               63
7             West Germany     204      5               40
8   United Team of Germany     118      3               39
9                  Germany     656     17               38
10           Great Britain     918     29               31
11                  France     752     29               25
12                   Japan     497     22               22
13                   Italy     620     27               22
14               Australia     547     27               20
15                 Ukraine     139      7               19
16                  Sweden     503     27               18
17                 Hungary     511     27               18
18             South Korea     287     17               16
19                 Romania     308     20               15
20                    Cuba     235     16               14
21                  Poland     298     22               13
22                Bulgaria     224     17               13
23             Netherlands     322     26               12
24                  Canada     326     27               12
25                 Belarus      85      7               12
26                 Finland     305     26               11
27              Kazakhstan      72      7               10
28          Czech Republic      67      7                9
29                   Spain     168     20                8
30              Mixed team      25      3                8
31                   Kenya     113     13                8
32          Czechoslovakia     143     16                8
33             Switzerland     207     28                7
34                 Denmark     205     28                7
35                  Brazil     150     20                7
36              Azerbaijan      49      7                7
37                  Serbia      24      4                6
38                  Norway     163     25                6
39             New Zealand     137     22                6
40                  Greece     121     20                6
41                 Belgium     163     26                6
42             Australasia      12      2                6
43              Yugoslavia      90     16                5
44              Uzbekistan      36      7                5
45                  Turkey     104     18                5
46             North Korea      55     10                5
47                 Jamaica      87     16                5
48                 Georgia      40      7                5
49                 Croatia      41      8                5

### Medals obtained while hosting

In [ ]:
query_medals_per_host_country ='''
SELECT 
Host_Country, SUM(total_medals) AS medals, SUM(Gold) AS Gold,
SUM(Silver) AS Silver, SUM(Bronze) AS Bronze,
COUNT(*) AS total_hosting,
28 AS total_olympics
FROM olympic_medals
WHERE Host_Country = Country_Name
GROUP BY Host_Country
ORDER BY total_hosting DESC
LIMIT 50;
'''
pd.read_sql_query(query_medals_per_host_country, conn)

     Host_country  medals  Gold  Silver  Bronze  total_hosting  total_olympics
0   United States     609   244     203     162              4              28
1   Great Britain     234    88      82      64              3              28
2           Japan      87    43      19      25              2              28
3          Greece      63    16      24      23              2              28
4          France     140    40      53      47              2              28
5    West Germany      40    13      11      16              1              28
6          Sweden      65    24      24      17              1              28
7           Spain      22    13       7       2              1              28
8    Soviet Union     195    80      69      46              1              28
9     South Korea      33    12      10      11              1              28
10    Netherlands      19     6       9       4              1              28
11         Mexico       9     3       3       3              1              28
12          Italy      36    13      10      13              1              28
13        Germany      89    33      26      30              1              28
14        Finland      22     6       3      13              1              28
15          China     100    48      22      30              1              28
16         Canada      11     0       5       6              1              28
17         Brazil      19     7       6       6              1              28
18        Belgium      42    16      12      14              1              28
19      Australia      58    16      25      17              1              28

### Comparing medals obtained when hosting/not-hosting

In [ ]:
query_medals_when_hosting_or_not = '''
SELECT Host_Country, 
'Hosting' AS Type, 
COUNT(*) AS total_hosting,
28 AS total_olympics, 
SUM(total_medals) AS medals, 
SUM(Gold) AS Gold,
SUM(Silver) AS Silver, 
SUM(Bronze) AS Bronze
FROM olympic_medals
WHERE Host_Country = Country_Name
GROUP BY Host_Country

UNION

SELECT Country_Name, 
'Not Hosting' AS Type,
'-' AS total_hosting,
28 AS total_olympics,
SUM(total_medals) AS medals,
SUM(Gold) AS Gold,
SUM(Silver) AS Silver,
SUM(Bronze) AS Bronze
FROM olympic_medals
WHERE Country_Name IN (SELECT DISTINCT Host_Country FROM olympic_medals) 
AND Host_Country <> Country_Name
GROUP BY Country_Name
ORDER BY Host_Country ASC, Type ASC;
'''
pd.read_sql_query(query_medals_when_hosting_or_not, conn)
# As we can see most countries do significantly better when hosting sometimes obtaining more than 20% of their total medals when hosting
# Greece has even obtained more medals when hosting compared to when not!!!

,Host_country,Type,total_hosting,total_olympics,medals,Gold,Silver,Bronze
0,Australia,Hosting,1,28,58,16,25,17
1,Australia,Not Hosting,-,28,489,148,148,193
2,Belgium,Hosting,1,28,42,16,12,14
3,Belgium,Not Hosting,-,28,121,30,45,46
4,Brazil,Hosting,1,28,19,7,6,6
5,Brazil,Not Hosting,-,28,131,30,36,65
6,Canada,Hosting,1,28,11,0,5,6
7,Canada,Not Hosting,-,28,315,71,104,140
8,China,Hosting,1,28,100,48,22,30
9,China,Not Hosting,-,28,534,214,177,143
10,Finland,Hosting,1,28,22,6,3,13
11,Finland,Not Hosting,-,28,283,95,82,106
12,France,Hosting,2,28,140,40,53,47
13,France,Not Hosting,-,28,612,183,199,230
14,Germany,Hosting,1,28,89,33,26,30
15,Germany,Not Hosting,-,28,567,169,181,217
16,Great Britain,Hosting,3,28,234,88,82,64
17,Great Britain,Not Hosting,-,28,684,196,237,251
18,Greece,Hosting,2,28,63,16,24,23
19,Greece,Not Hosting,-,28,58,19,21,18
20,Italy,Hosting,1,28,36,13,10,13
21,Italy,Not Hosting,-,28,584,206,178,200
22,Japan,Hosting,2,28,87,43,19,25
23,Japan,Not Hosting,-,28,410,126,131,153
24,Mexico,Hosting,1,28,9,3,3,3
25,Mexico,Not Hosting,-,28,63,10,21,32
26,Netherlands,Hosting,1,28,19,6,9,4
27,Netherlands,Not Hosting,-,28,303,89,96,118
28,South Korea,Hosting,1,28,33,12,10,11
29,South Korea,Not Hosting,-,28,254,84,81,89
30,Soviet Union,Hosting,1,28,195,80,69,46
31,Soviet Union,Not Hosting,-,28,815,315,250,250
32,Spain,Hosting,1,28,22,13,7,2
33,Spain,Not Hosting,-,28,146,35,65,46
34,Sweden,Hosting,1,28,65,24,24,17
35,Sweden,Not Hosting,-,28,438,124,152,162
36,United States,Hosting,4,28,609,244,203,162
37,United States,Not Hosting,-,28,2021,816,629,576
38,West Germany,Hosting,1,28,40,13,11,16
39,West Germany,Not Hosting,-,28,164,43,56,65